### ISSUE TITLE
Other accounts cannot watch this video.

### ISSUE THREAD

**Issue by tiktok666** [SrMilton/MTAM-Tiktok#1]
Hello there! After the video is processed, you can upload a video longer than one minute, but other accounts cannot watch this video. And he couldn't watch this video in full on tiktok. For example, a one-and-a-half minute video can only be watched for the first 30 seconds after being processed and uploaded to tiktok. (Web upload)

**Comment by SrMilton** [comment]
Sorry but you are wrong, everyone can see your video longer than a minute, but you can't upload videos with copyrights, in this case your video will be blocked.

Here is my account witch i used to test this program:
http://tiktok.com/@morethanminutescript
As you can see, all the videos has more than a minute and everyone can see this (see the comments)

If you don't have any issue, please close ;)

Thanks for using MTAM

**Comment by tiktok666** [comment]
Thank you very much. I saw your tiktok account "morethanminutescript". The latest video was uploaded on February 3, 2021. Have you tried to upload a video recently?
The video I uploaded was shot by myself, and there is no music, and there is no copyright issue.

**Comment by SrMilton** [comment]
Looks like Tiktok applyed some filter when we upload videos to prevent videos with more than a minute, i'll fix it when i have time.

Thanks for reporting this bug, i'll fix or i'll try to create a bypass (if it's possible).

**Comment by tiktok666** [comment]
Thank you very much and look forward to your update

**Comment by SrMilton** [comment]
Tiktok patched it years ago and now implemented this function natively.
